// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:pacs.010.001.05
package pacs_010_001_05

import (
	"encoding/xml"
)

// Element
type Document struct {
	XMLName xml.Name `xml:"Document"`

	FIDrctDbt FinancialInstitutionDirectDebitV05 `xml:",any"`
}

// XSD ComplexType declarations

type AccountIdentification4Choice struct {
	XMLName xml.Name

	IBAN *IBAN2007Identifier `xml:"IBAN"`

	Othr *GenericAccountIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type AccountSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalAccountIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ActiveCurrencyAndAmount struct {
	XMLName xml.Name

	Ccy ActiveCurrencyCode `xml:"Ccy,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type AddressType3Choice struct {
	XMLName xml.Name

	Cd *AddressType2Code `xml:"Cd"`

	Prtry *GenericIdentification30 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type BranchAndFinancialInstitutionIdentification6 struct {
	XMLName xml.Name

	FinInstnId FinancialInstitutionIdentification18 `xml:"FinInstnId"`

	BrnchId *BranchData3 `xml:"BrnchId"`

	InnerXml string `xml:",innerxml"`
}

type BranchData3 struct {
	XMLName xml.Name

	Id *Max35Text `xml:"Id"`

	LEI *LEIIdentifier `xml:"LEI"`

	Nm *Max140Text `xml:"Nm"`

	PstlAdr *PostalAddress24 `xml:"PstlAdr"`

	InnerXml string `xml:",innerxml"`
}

type CashAccount40 struct {
	XMLName xml.Name

	Id *AccountIdentification4Choice `xml:"Id"`

	Tp *CashAccountType2Choice `xml:"Tp"`

	Ccy *ActiveOrHistoricCurrencyCode `xml:"Ccy"`

	Nm *Max70Text `xml:"Nm"`

	Prxy *ProxyAccountIdentification1 `xml:"Prxy"`

	InnerXml string `xml:",innerxml"`
}

type CashAccountType2Choice struct {
	XMLName xml.Name

	Cd *ExternalCashAccountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type CategoryPurpose1Choice struct {
	XMLName xml.Name

	Cd *ExternalCategoryPurpose1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ClearingSystemIdentification2Choice struct {
	XMLName xml.Name

	Cd *ExternalClearingSystemIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ClearingSystemMemberIdentification2 struct {
	XMLName xml.Name

	ClrSysId *ClearingSystemIdentification2Choice `xml:"ClrSysId"`

	MmbId Max35Text `xml:"MmbId"`

	InnerXml string `xml:",innerxml"`
}

type CreditTransferTransaction53 struct {
	XMLName xml.Name

	CdtId Max35Text `xml:"CdtId"`

	BtchBookg *BatchBookingIndicator `xml:"BtchBookg"`

	PmtTpInf *PaymentTypeInformation28 `xml:"PmtTpInf"`

	TtlIntrBkSttlmAmt *ActiveCurrencyAndAmount `xml:"TtlIntrBkSttlmAmt"`

	IntrBkSttlmDt *ISODate `xml:"IntrBkSttlmDt"`

	SttlmTmIndctn *SettlementDateTimeIndication1 `xml:"SttlmTmIndctn"`

	InstgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstgAgt"`

	InstdAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstdAgt"`

	IntrmyAgt1 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt1"`

	IntrmyAgt1Acct *CashAccount40 `xml:"IntrmyAgt1Acct"`

	IntrmyAgt2 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt2"`

	IntrmyAgt2Acct *CashAccount40 `xml:"IntrmyAgt2Acct"`

	IntrmyAgt3 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt3"`

	IntrmyAgt3Acct *CashAccount40 `xml:"IntrmyAgt3Acct"`

	CdtrAgt *BranchAndFinancialInstitutionIdentification6 `xml:"CdtrAgt"`

	CdtrAgtAcct *CashAccount40 `xml:"CdtrAgtAcct"`

	Cdtr BranchAndFinancialInstitutionIdentification6 `xml:"Cdtr"`

	CdtrAcct *CashAccount40 `xml:"CdtrAcct"`

	UltmtCdtr *BranchAndFinancialInstitutionIdentification6 `xml:"UltmtCdtr"`

	InstrForCdtrAgt []InstructionForCreditorAgent3 `xml:"InstrForCdtrAgt"`

	DrctDbtTxInf []DirectDebitTransactionInformation27 `xml:"DrctDbtTxInf"`

	SplmtryData []SupplementaryData1 `xml:"SplmtryData"`

	InnerXml string `xml:",innerxml"`
}

type DirectDebitTransactionInformation27 struct {
	XMLName xml.Name

	PmtId PaymentIdentification13 `xml:"PmtId"`

	PmtTpInf *PaymentTypeInformation28 `xml:"PmtTpInf"`

	IntrBkSttlmAmt ActiveCurrencyAndAmount `xml:"IntrBkSttlmAmt"`

	IntrBkSttlmDt *ISODate `xml:"IntrBkSttlmDt"`

	SttlmPrty *Priority3Code `xml:"SttlmPrty"`

	SttlmTmIndctn *SettlementDateTimeIndication1 `xml:"SttlmTmIndctn"`

	SttlmTmReq *SettlementTimeRequest2 `xml:"SttlmTmReq"`

	UltmtDbtr *BranchAndFinancialInstitutionIdentification6 `xml:"UltmtDbtr"`

	Dbtr BranchAndFinancialInstitutionIdentification6 `xml:"Dbtr"`

	DbtrAcct *CashAccount40 `xml:"DbtrAcct"`

	DbtrAgt *BranchAndFinancialInstitutionIdentification6 `xml:"DbtrAgt"`

	DbtrAgtAcct *CashAccount40 `xml:"DbtrAgtAcct"`

	InstrForDbtrAgt *Max210Text `xml:"InstrForDbtrAgt"`

	Purp *Purpose2Choice `xml:"Purp"`

	RmtInf *RemittanceInformation2 `xml:"RmtInf"`

	InnerXml string `xml:",innerxml"`
}

type FinancialIdentificationSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalFinancialInstitutionIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type FinancialInstitutionDirectDebitV05 struct {
	XMLName xml.Name

	GrpHdr GroupHeader92 `xml:"GrpHdr"`

	CdtInstr []CreditTransferTransaction53 `xml:"CdtInstr"`

	SplmtryData []SupplementaryData1 `xml:"SplmtryData"`

	InnerXml string `xml:",innerxml"`
}

type FinancialInstitutionIdentification18 struct {
	XMLName xml.Name

	BICFI *BICFIDec2014Identifier `xml:"BICFI"`

	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`

	LEI *LEIIdentifier `xml:"LEI"`

	Nm *Max140Text `xml:"Nm"`

	PstlAdr *PostalAddress24 `xml:"PstlAdr"`

	Othr *GenericFinancialIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type GenericAccountIdentification1 struct {
	XMLName xml.Name

	Id Max34Text `xml:"Id"`

	SchmeNm *AccountSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericFinancialIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericIdentification30 struct {
	XMLName xml.Name

	Id Exact4AlphaNumericText `xml:"Id"`

	Issr Max35Text `xml:"Issr"`

	SchmeNm *Max35Text `xml:"SchmeNm"`

	InnerXml string `xml:",innerxml"`
}

type GroupHeader92 struct {
	XMLName xml.Name

	MsgId Max35Text `xml:"MsgId"`

	CreDtTm ISODateTime `xml:"CreDtTm"`

	NbOfTxs Max15NumericText `xml:"NbOfTxs"`

	CtrlSum *DecimalNumber `xml:"CtrlSum"`

	InstgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstgAgt"`

	InstdAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstdAgt"`

	InnerXml string `xml:",innerxml"`
}

type InstructionForCreditorAgent3 struct {
	XMLName xml.Name

	Cd *ExternalCreditorAgentInstruction1Code `xml:"Cd"`

	InstrInf *Max140Text `xml:"InstrInf"`

	InnerXml string `xml:",innerxml"`
}

type LocalInstrument2Choice struct {
	XMLName xml.Name

	Cd *ExternalLocalInstrument1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type PaymentIdentification13 struct {
	XMLName xml.Name

	InstrId *Max35Text `xml:"InstrId"`

	EndToEndId Max35Text `xml:"EndToEndId"`

	TxId *Max35Text `xml:"TxId"`

	UETR *UUIDv4Identifier `xml:"UETR"`

	ClrSysRef *Max35Text `xml:"ClrSysRef"`

	InnerXml string `xml:",innerxml"`
}

type PaymentTypeInformation28 struct {
	XMLName xml.Name

	InstrPrty *Priority2Code `xml:"InstrPrty"`

	ClrChanl *ClearingChannel2Code `xml:"ClrChanl"`

	SvcLvl []ServiceLevel8Choice `xml:"SvcLvl"`

	LclInstrm *LocalInstrument2Choice `xml:"LclInstrm"`

	CtgyPurp *CategoryPurpose1Choice `xml:"CtgyPurp"`

	InnerXml string `xml:",innerxml"`
}

type PostalAddress24 struct {
	XMLName xml.Name

	AdrTp *AddressType3Choice `xml:"AdrTp"`

	Dept *Max70Text `xml:"Dept"`

	SubDept *Max70Text `xml:"SubDept"`

	StrtNm *Max70Text `xml:"StrtNm"`

	BldgNb *Max16Text `xml:"BldgNb"`

	BldgNm *Max35Text `xml:"BldgNm"`

	Flr *Max70Text `xml:"Flr"`

	PstBx *Max16Text `xml:"PstBx"`

	Room *Max70Text `xml:"Room"`

	PstCd *Max16Text `xml:"PstCd"`

	TwnNm *Max35Text `xml:"TwnNm"`

	TwnLctnNm *Max35Text `xml:"TwnLctnNm"`

	DstrctNm *Max35Text `xml:"DstrctNm"`

	CtrySubDvsn *Max35Text `xml:"CtrySubDvsn"`

	Ctry *CountryCode `xml:"Ctry"`

	AdrLine []Max70Text `xml:"AdrLine"`

	InnerXml string `xml:",innerxml"`
}

type ProxyAccountIdentification1 struct {
	XMLName xml.Name

	Tp *ProxyAccountType1Choice `xml:"Tp"`

	Id Max2048Text `xml:"Id"`

	InnerXml string `xml:",innerxml"`
}

type ProxyAccountType1Choice struct {
	XMLName xml.Name

	Cd *ExternalProxyAccountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type Purpose2Choice struct {
	XMLName xml.Name

	Cd *ExternalPurpose1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceInformation2 struct {
	XMLName xml.Name

	Ustrd []Max140Text `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

type ServiceLevel8Choice struct {
	XMLName xml.Name

	Cd *ExternalServiceLevel1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type SettlementDateTimeIndication1 struct {
	XMLName xml.Name

	DbtDtTm *ISODateTime `xml:"DbtDtTm"`

	CdtDtTm *ISODateTime `xml:"CdtDtTm"`

	InnerXml string `xml:",innerxml"`
}

type SettlementTimeRequest2 struct {
	XMLName xml.Name

	CLSTm *ISOTime `xml:"CLSTm"`

	TillTm *ISOTime `xml:"TillTm"`

	FrTm *ISOTime `xml:"FrTm"`

	RjctTm *ISOTime `xml:"RjctTm"`

	InnerXml string `xml:",innerxml"`
}

type SupplementaryData1 struct {
	XMLName xml.Name

	PlcAndNm *Max350Text `xml:"PlcAndNm"`

	Envlp SupplementaryDataEnvelope1 `xml:"Envlp"`

	InnerXml string `xml:",innerxml"`
}

type SupplementaryDataEnvelope1 struct {
	XMLName xml.Name

	InnerXml string `xml:",innerxml"`
}

// XSD SimpleType declarations

type ActiveCurrencyAndAmountSimpleType float64

type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyCode string

type AddressType2Code string

const AddressType2CodeAddr AddressType2Code = "ADDR"

const AddressType2CodePbox AddressType2Code = "PBOX"

const AddressType2CodeHome AddressType2Code = "HOME"

const AddressType2CodeBizz AddressType2Code = "BIZZ"

const AddressType2CodeMlto AddressType2Code = "MLTO"

const AddressType2CodeDlvy AddressType2Code = "DLVY"

type BICFIDec2014Identifier string

type BatchBookingIndicator bool

type ClearingChannel2Code string

const ClearingChannel2CodeRtgs ClearingChannel2Code = "RTGS"

const ClearingChannel2CodeRtns ClearingChannel2Code = "RTNS"

const ClearingChannel2CodeMpns ClearingChannel2Code = "MPNS"

const ClearingChannel2CodeBook ClearingChannel2Code = "BOOK"

type CountryCode string

type DecimalNumber float64

type Exact4AlphaNumericText string

type ExternalAccountIdentification1Code string

type ExternalCashAccountType1Code string

type ExternalCategoryPurpose1Code string

type ExternalClearingSystemIdentification1Code string

type ExternalCreditorAgentInstruction1Code string

type ExternalFinancialInstitutionIdentification1Code string

type ExternalLocalInstrument1Code string

type ExternalProxyAccountType1Code string

type ExternalPurpose1Code string

type ExternalServiceLevel1Code string

type IBAN2007Identifier string

type ISODate string

type ISODateTime string

type ISOTime string

type LEIIdentifier string

type Max140Text string

type Max15NumericText string

type Max16Text string

type Max2048Text string

type Max210Text string

type Max34Text string

type Max350Text string

type Max35Text string

type Max70Text string

type Priority2Code string

const Priority2CodeHigh Priority2Code = "HIGH"

const Priority2CodeNorm Priority2Code = "NORM"

type Priority3Code string

const Priority3CodeUrgt Priority3Code = "URGT"

const Priority3CodeHigh Priority3Code = "HIGH"

const Priority3CodeNorm Priority3Code = "NORM"

type UUIDv4Identifier string
