// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for urn:iso:std:iso:20022:tech:xsd:camt.054.001.10
package camt_054_001_10

import (
	"encoding/xml"
)

// Element
type Document struct {
	XMLName xml.Name `xml:"Document"`

	BkToCstmrDbtCdtNtfctn BankToCustomerDebitCreditNotificationV10 `xml:",any"`
}

// XSD ComplexType declarations

type AccountIdentification4Choice struct {
	XMLName xml.Name

	IBAN *IBAN2007Identifier `xml:"IBAN"`

	Othr *GenericAccountIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type AccountInterest4 struct {
	XMLName xml.Name

	Tp *InterestType1Choice `xml:"Tp"`

	Rate []Rate4 `xml:"Rate"`

	FrToDt *DateTimePeriod1 `xml:"FrToDt"`

	Rsn *Max35Text `xml:"Rsn"`

	Tax *TaxCharges2 `xml:"Tax"`

	InnerXml string `xml:",innerxml"`
}

type AccountNotification20 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	NtfctnPgntn *Pagination1 `xml:"NtfctnPgntn"`

	ElctrncSeqNb *Number `xml:"ElctrncSeqNb"`

	RptgSeq *SequenceRange1Choice `xml:"RptgSeq"`

	LglSeqNb *Number `xml:"LglSeqNb"`

	CreDtTm *ISODateTime `xml:"CreDtTm"`

	FrToDt *DateTimePeriod1 `xml:"FrToDt"`

	CpyDplctInd *CopyDuplicate1Code `xml:"CpyDplctInd"`

	RptgSrc *ReportingSource1Choice `xml:"RptgSrc"`

	Acct CashAccount41 `xml:"Acct"`

	RltdAcct *CashAccount40 `xml:"RltdAcct"`

	Intrst []AccountInterest4 `xml:"Intrst"`

	TxsSummry *TotalTransactions6 `xml:"TxsSummry"`

	Ntry []ReportEntry12 `xml:"Ntry"`

	AddtlNtfctnInf *Max500Text `xml:"AddtlNtfctnInf"`

	InnerXml string `xml:",innerxml"`
}

type AccountSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalAccountIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ActiveCurrencyAndAmount struct {
	XMLName xml.Name

	Ccy ActiveCurrencyCode `xml:"Ccy,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type ActiveOrHistoricCurrencyAnd13DecimalAmount struct {
	XMLName xml.Name

	Ccy ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type ActiveOrHistoricCurrencyAndAmount struct {
	XMLName xml.Name

	Ccy ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`

	Text     string `xml:",chardata"`
	InnerXml string `xml:",innerxml"`
}

type ActiveOrHistoricCurrencyAndAmountRange2 struct {
	XMLName xml.Name

	Amt ImpliedCurrencyAmountRange1Choice `xml:"Amt"`

	CdtDbtInd *CreditDebitCode `xml:"CdtDbtInd"`

	Ccy ActiveOrHistoricCurrencyCode `xml:"Ccy"`

	InnerXml string `xml:",innerxml"`
}

type AddressType3Choice struct {
	XMLName xml.Name

	Cd *AddressType2Code `xml:"Cd"`

	Prtry *GenericIdentification30 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type AmountAndCurrencyExchange3 struct {
	XMLName xml.Name

	InstdAmt *AmountAndCurrencyExchangeDetails3 `xml:"InstdAmt"`

	TxAmt *AmountAndCurrencyExchangeDetails3 `xml:"TxAmt"`

	CntrValAmt *AmountAndCurrencyExchangeDetails3 `xml:"CntrValAmt"`

	AnncdPstngAmt *AmountAndCurrencyExchangeDetails3 `xml:"AnncdPstngAmt"`

	PrtryAmt []AmountAndCurrencyExchangeDetails4 `xml:"PrtryAmt"`

	InnerXml string `xml:",innerxml"`
}

type AmountAndCurrencyExchangeDetails3 struct {
	XMLName xml.Name

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CcyXchg *CurrencyExchange5 `xml:"CcyXchg"`

	InnerXml string `xml:",innerxml"`
}

type AmountAndCurrencyExchangeDetails4 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CcyXchg *CurrencyExchange5 `xml:"CcyXchg"`

	InnerXml string `xml:",innerxml"`
}

type AmountAndDirection35 struct {
	XMLName xml.Name

	Amt NonNegativeDecimalNumber `xml:"Amt"`

	CdtDbtInd CreditDebitCode `xml:"CdtDbtInd"`

	InnerXml string `xml:",innerxml"`
}

type AmountRangeBoundary1 struct {
	XMLName xml.Name

	BdryAmt ImpliedCurrencyAndAmount `xml:"BdryAmt"`

	Incl YesNoIndicator `xml:"Incl"`

	InnerXml string `xml:",innerxml"`
}

type BankToCustomerDebitCreditNotificationV10 struct {
	XMLName xml.Name

	GrpHdr GroupHeader81 `xml:"GrpHdr"`

	Ntfctn []AccountNotification20 `xml:"Ntfctn"`

	SplmtryData []SupplementaryData1 `xml:"SplmtryData"`

	InnerXml string `xml:",innerxml"`
}

type BankTransactionCodeStructure4 struct {
	XMLName xml.Name

	Domn *BankTransactionCodeStructure5 `xml:"Domn"`

	Prtry *ProprietaryBankTransactionCodeStructure1 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type BankTransactionCodeStructure5 struct {
	XMLName xml.Name

	Cd ExternalBankTransactionDomain1Code `xml:"Cd"`

	Fmly BankTransactionCodeStructure6 `xml:"Fmly"`

	InnerXml string `xml:",innerxml"`
}

type BankTransactionCodeStructure6 struct {
	XMLName xml.Name

	Cd ExternalBankTransactionFamily1Code `xml:"Cd"`

	SubFmlyCd ExternalBankTransactionSubFamily1Code `xml:"SubFmlyCd"`

	InnerXml string `xml:",innerxml"`
}

type BatchInformation2 struct {
	XMLName xml.Name

	MsgId *Max35Text `xml:"MsgId"`

	PmtInfId *Max35Text `xml:"PmtInfId"`

	NbOfTxs *Max15NumericText `xml:"NbOfTxs"`

	TtlAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlAmt"`

	CdtDbtInd *CreditDebitCode `xml:"CdtDbtInd"`

	InnerXml string `xml:",innerxml"`
}

type BranchAndFinancialInstitutionIdentification6 struct {
	XMLName xml.Name

	FinInstnId FinancialInstitutionIdentification18 `xml:"FinInstnId"`

	BrnchId *BranchData3 `xml:"BrnchId"`

	InnerXml string `xml:",innerxml"`
}

type BranchData3 struct {
	XMLName xml.Name

	Id *Max35Text `xml:"Id"`

	LEI *LEIIdentifier `xml:"LEI"`

	Nm *Max140Text `xml:"Nm"`

	PstlAdr *PostalAddress24 `xml:"PstlAdr"`

	InnerXml string `xml:",innerxml"`
}

type CardAggregated2 struct {
	XMLName xml.Name

	AddtlSvc *CardPaymentServiceType2Code `xml:"AddtlSvc"`

	TxCtgy *ExternalCardTransactionCategory1Code `xml:"TxCtgy"`

	SaleRcncltnId *Max35Text `xml:"SaleRcncltnId"`

	SeqNbRg *CardSequenceNumberRange1 `xml:"SeqNbRg"`

	TxDtRg *DateOrDateTimePeriod1Choice `xml:"TxDtRg"`

	InnerXml string `xml:",innerxml"`
}

type CardEntry5 struct {
	XMLName xml.Name

	Card *PaymentCard4 `xml:"Card"`

	POI *PointOfInteraction1 `xml:"POI"`

	AggtdNtry *CardAggregated2 `xml:"AggtdNtry"`

	PrePdAcct *CashAccount40 `xml:"PrePdAcct"`

	InnerXml string `xml:",innerxml"`
}

type CardIndividualTransaction2 struct {
	XMLName xml.Name

	ICCRltdData *Max1025Text `xml:"ICCRltdData"`

	PmtCntxt *PaymentContext3 `xml:"PmtCntxt"`

	AddtlSvc *CardPaymentServiceType2Code `xml:"AddtlSvc"`

	TxCtgy *ExternalCardTransactionCategory1Code `xml:"TxCtgy"`

	SaleRcncltnId *Max35Text `xml:"SaleRcncltnId"`

	SaleRefNb *Max35Text `xml:"SaleRefNb"`

	RePresntmntRsn *ExternalRePresentmentReason1Code `xml:"RePresntmntRsn"`

	SeqNb *Max35Text `xml:"SeqNb"`

	TxId *TransactionIdentifier1 `xml:"TxId"`

	Pdct *Product2 `xml:"Pdct"`

	VldtnDt *ISODate `xml:"VldtnDt"`

	VldtnSeqNb *Max35Text `xml:"VldtnSeqNb"`

	InnerXml string `xml:",innerxml"`
}

type CardSecurityInformation1 struct {
	XMLName xml.Name

	CSCMgmt CSCManagement1Code `xml:"CSCMgmt"`

	CSCVal *Min3Max4NumericText `xml:"CSCVal"`

	InnerXml string `xml:",innerxml"`
}

type CardSequenceNumberRange1 struct {
	XMLName xml.Name

	FrstTx *Max35Text `xml:"FrstTx"`

	LastTx *Max35Text `xml:"LastTx"`

	InnerXml string `xml:",innerxml"`
}

type CardTransaction18 struct {
	XMLName xml.Name

	Card *PaymentCard4 `xml:"Card"`

	POI *PointOfInteraction1 `xml:"POI"`

	Tx *CardTransaction3Choice `xml:"Tx"`

	PrePdAcct *CashAccount40 `xml:"PrePdAcct"`

	InnerXml string `xml:",innerxml"`
}

type CardTransaction3Choice struct {
	XMLName xml.Name

	Aggtd *CardAggregated2 `xml:"Aggtd"`

	Indv *CardIndividualTransaction2 `xml:"Indv"`

	InnerXml string `xml:",innerxml"`
}

type CardholderAuthentication2 struct {
	XMLName xml.Name

	AuthntcnMtd AuthenticationMethod1Code `xml:"AuthntcnMtd"`

	AuthntcnNtty AuthenticationEntity1Code `xml:"AuthntcnNtty"`

	InnerXml string `xml:",innerxml"`
}

type CashAccount40 struct {
	XMLName xml.Name

	Id *AccountIdentification4Choice `xml:"Id"`

	Tp *CashAccountType2Choice `xml:"Tp"`

	Ccy *ActiveOrHistoricCurrencyCode `xml:"Ccy"`

	Nm *Max70Text `xml:"Nm"`

	Prxy *ProxyAccountIdentification1 `xml:"Prxy"`

	InnerXml string `xml:",innerxml"`
}

type CashAccount41 struct {
	XMLName xml.Name

	Id *AccountIdentification4Choice `xml:"Id"`

	Tp *CashAccountType2Choice `xml:"Tp"`

	Ccy *ActiveOrHistoricCurrencyCode `xml:"Ccy"`

	Nm *Max70Text `xml:"Nm"`

	Prxy *ProxyAccountIdentification1 `xml:"Prxy"`

	Ownr *PartyIdentification135 `xml:"Ownr"`

	Svcr *BranchAndFinancialInstitutionIdentification6 `xml:"Svcr"`

	InnerXml string `xml:",innerxml"`
}

type CashAccountType2Choice struct {
	XMLName xml.Name

	Cd *ExternalCashAccountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type CashAvailability1 struct {
	XMLName xml.Name

	Dt CashAvailabilityDate1Choice `xml:"Dt"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd CreditDebitCode `xml:"CdtDbtInd"`

	InnerXml string `xml:",innerxml"`
}

type CashAvailabilityDate1Choice struct {
	XMLName xml.Name

	NbOfDays *Max15PlusSignedNumericText `xml:"NbOfDays"`

	ActlDt *ISODate `xml:"ActlDt"`

	InnerXml string `xml:",innerxml"`
}

type CashDeposit1 struct {
	XMLName xml.Name

	NoteDnmtn ActiveCurrencyAndAmount `xml:"NoteDnmtn"`

	NbOfNotes Max15NumericText `xml:"NbOfNotes"`

	Amt ActiveCurrencyAndAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type CategoryPurpose1Choice struct {
	XMLName xml.Name

	Cd *ExternalCategoryPurpose1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ChargeType3Choice struct {
	XMLName xml.Name

	Cd *ExternalChargeType1Code `xml:"Cd"`

	Prtry *GenericIdentification3 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type Charges6 struct {
	XMLName xml.Name

	TtlChrgsAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlChrgsAndTaxAmt"`

	Rcrd []ChargesRecord3 `xml:"Rcrd"`

	InnerXml string `xml:",innerxml"`
}

type ChargesRecord3 struct {
	XMLName xml.Name

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd *CreditDebitCode `xml:"CdtDbtInd"`

	ChrgInclInd *ChargeIncludedIndicator `xml:"ChrgInclInd"`

	Tp *ChargeType3Choice `xml:"Tp"`

	Rate *PercentageRate `xml:"Rate"`

	Br *ChargeBearerType1Code `xml:"Br"`

	Agt *BranchAndFinancialInstitutionIdentification6 `xml:"Agt"`

	Tax *TaxCharges2 `xml:"Tax"`

	InnerXml string `xml:",innerxml"`
}

type ClearingSystemIdentification2Choice struct {
	XMLName xml.Name

	Cd *ExternalClearingSystemIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ClearingSystemMemberIdentification2 struct {
	XMLName xml.Name

	ClrSysId *ClearingSystemIdentification2Choice `xml:"ClrSysId"`

	MmbId Max35Text `xml:"MmbId"`

	InnerXml string `xml:",innerxml"`
}

type Contact4 struct {
	XMLName xml.Name

	NmPrfx *NamePrefix2Code `xml:"NmPrfx"`

	Nm *Max140Text `xml:"Nm"`

	PhneNb *PhoneNumber `xml:"PhneNb"`

	MobNb *PhoneNumber `xml:"MobNb"`

	FaxNb *PhoneNumber `xml:"FaxNb"`

	EmailAdr *Max2048Text `xml:"EmailAdr"`

	EmailPurp *Max35Text `xml:"EmailPurp"`

	JobTitl *Max35Text `xml:"JobTitl"`

	Rspnsblty *Max35Text `xml:"Rspnsblty"`

	Dept *Max70Text `xml:"Dept"`

	Othr []OtherContact1 `xml:"Othr"`

	PrefrdMtd *PreferredContactMethod1Code `xml:"PrefrdMtd"`

	InnerXml string `xml:",innerxml"`
}

type CorporateAction9 struct {
	XMLName xml.Name

	EvtTp Max35Text `xml:"EvtTp"`

	EvtId Max35Text `xml:"EvtId"`

	InnerXml string `xml:",innerxml"`
}

type CreditorReferenceInformation2 struct {
	XMLName xml.Name

	Tp *CreditorReferenceType2 `xml:"Tp"`

	Ref *Max35Text `xml:"Ref"`

	InnerXml string `xml:",innerxml"`
}

type CreditorReferenceType1Choice struct {
	XMLName xml.Name

	Cd *DocumentType3Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type CreditorReferenceType2 struct {
	XMLName xml.Name

	CdOrPrtry CreditorReferenceType1Choice `xml:"CdOrPrtry"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type CurrencyExchange5 struct {
	XMLName xml.Name

	SrcCcy ActiveOrHistoricCurrencyCode `xml:"SrcCcy"`

	TrgtCcy *ActiveOrHistoricCurrencyCode `xml:"TrgtCcy"`

	UnitCcy *ActiveOrHistoricCurrencyCode `xml:"UnitCcy"`

	XchgRate BaseOneRate `xml:"XchgRate"`

	CtrctId *Max35Text `xml:"CtrctId"`

	QtnDt *ISODateTime `xml:"QtnDt"`

	InnerXml string `xml:",innerxml"`
}

type DateAndDateTime2Choice struct {
	XMLName xml.Name

	Dt *ISODate `xml:"Dt"`

	DtTm *ISODateTime `xml:"DtTm"`

	InnerXml string `xml:",innerxml"`
}

type DateAndPlaceOfBirth1 struct {
	XMLName xml.Name

	BirthDt ISODate `xml:"BirthDt"`

	PrvcOfBirth *Max35Text `xml:"PrvcOfBirth"`

	CityOfBirth Max35Text `xml:"CityOfBirth"`

	CtryOfBirth CountryCode `xml:"CtryOfBirth"`

	InnerXml string `xml:",innerxml"`
}

type DateOrDateTimePeriod1Choice struct {
	XMLName xml.Name

	Dt *DatePeriod2 `xml:"Dt"`

	DtTm *DateTimePeriod1 `xml:"DtTm"`

	InnerXml string `xml:",innerxml"`
}

type DatePeriod2 struct {
	XMLName xml.Name

	FrDt ISODate `xml:"FrDt"`

	ToDt ISODate `xml:"ToDt"`

	InnerXml string `xml:",innerxml"`
}

type DateTimePeriod1 struct {
	XMLName xml.Name

	FrDtTm ISODateTime `xml:"FrDtTm"`

	ToDtTm ISODateTime `xml:"ToDtTm"`

	InnerXml string `xml:",innerxml"`
}

type DiscountAmountAndType1 struct {
	XMLName xml.Name

	Tp *DiscountAmountType1Choice `xml:"Tp"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type DiscountAmountType1Choice struct {
	XMLName xml.Name

	Cd *ExternalDiscountAmountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type DisplayCapabilities1 struct {
	XMLName xml.Name

	DispTp UserInterface2Code `xml:"DispTp"`

	NbOfLines Max3NumericText `xml:"NbOfLines"`

	LineWidth Max3NumericText `xml:"LineWidth"`

	InnerXml string `xml:",innerxml"`
}

type DocumentAdjustment1 struct {
	XMLName xml.Name

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd *CreditDebitCode `xml:"CdtDbtInd"`

	Rsn *Max4Text `xml:"Rsn"`

	AddtlInf *Max140Text `xml:"AddtlInf"`

	InnerXml string `xml:",innerxml"`
}

type DocumentLineIdentification1 struct {
	XMLName xml.Name

	Tp *DocumentLineType1 `xml:"Tp"`

	Nb *Max35Text `xml:"Nb"`

	RltdDt *ISODate `xml:"RltdDt"`

	InnerXml string `xml:",innerxml"`
}

type DocumentLineInformation1 struct {
	XMLName xml.Name

	Id []DocumentLineIdentification1 `xml:"Id"`

	Desc *Max2048Text `xml:"Desc"`

	Amt *RemittanceAmount3 `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type DocumentLineType1 struct {
	XMLName xml.Name

	CdOrPrtry DocumentLineType1Choice `xml:"CdOrPrtry"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type DocumentLineType1Choice struct {
	XMLName xml.Name

	Cd *ExternalDocumentLineType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type EntryDetails11 struct {
	XMLName xml.Name

	Btch *BatchInformation2 `xml:"Btch"`

	TxDtls []EntryTransaction12 `xml:"TxDtls"`

	InnerXml string `xml:",innerxml"`
}

type EntryStatus1Choice struct {
	XMLName xml.Name

	Cd *ExternalEntryStatus1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type EntryTransaction12 struct {
	XMLName xml.Name

	Refs *TransactionReferences6 `xml:"Refs"`

	Amt *ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd *CreditDebitCode `xml:"CdtDbtInd"`

	AmtDtls *AmountAndCurrencyExchange3 `xml:"AmtDtls"`

	Avlbty []CashAvailability1 `xml:"Avlbty"`

	BkTxCd *BankTransactionCodeStructure4 `xml:"BkTxCd"`

	Chrgs *Charges6 `xml:"Chrgs"`

	Intrst *TransactionInterest4 `xml:"Intrst"`

	RltdPties *TransactionParties9 `xml:"RltdPties"`

	RltdAgts *TransactionAgents5 `xml:"RltdAgts"`

	LclInstrm *LocalInstrument2Choice `xml:"LclInstrm"`

	PmtTpInf *PaymentTypeInformation27 `xml:"PmtTpInf"`

	Purp *Purpose2Choice `xml:"Purp"`

	RltdRmtInf []RemittanceLocation7 `xml:"RltdRmtInf"`

	RmtInf *RemittanceInformation21 `xml:"RmtInf"`

	RltdDts *TransactionDates3 `xml:"RltdDts"`

	RltdPric *TransactionPrice4Choice `xml:"RltdPric"`

	RltdQties []TransactionQuantities3Choice `xml:"RltdQties"`

	FinInstrmId *SecurityIdentification19 `xml:"FinInstrmId"`

	Tax *TaxInformation10 `xml:"Tax"`

	RtrInf *PaymentReturnReason5 `xml:"RtrInf"`

	CorpActn *CorporateAction9 `xml:"CorpActn"`

	SfkpgAcct *SecuritiesAccount19 `xml:"SfkpgAcct"`

	CshDpst []CashDeposit1 `xml:"CshDpst"`

	CardTx *CardTransaction18 `xml:"CardTx"`

	AddtlTxInf *Max500Text `xml:"AddtlTxInf"`

	SplmtryData []SupplementaryData1 `xml:"SplmtryData"`

	InnerXml string `xml:",innerxml"`
}

type FinancialIdentificationSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalFinancialInstitutionIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type FinancialInstitutionIdentification18 struct {
	XMLName xml.Name

	BICFI *BICFIDec2014Identifier `xml:"BICFI"`

	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`

	LEI *LEIIdentifier `xml:"LEI"`

	Nm *Max140Text `xml:"Nm"`

	PstlAdr *PostalAddress24 `xml:"PstlAdr"`

	Othr *GenericFinancialIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type FinancialInstrumentQuantity1Choice struct {
	XMLName xml.Name

	Unit *DecimalNumber `xml:"Unit"`

	FaceAmt *ImpliedCurrencyAndAmount `xml:"FaceAmt"`

	AmtsdVal *ImpliedCurrencyAndAmount `xml:"AmtsdVal"`

	InnerXml string `xml:",innerxml"`
}

type FromToAmountRange1 struct {
	XMLName xml.Name

	FrAmt AmountRangeBoundary1 `xml:"FrAmt"`

	ToAmt AmountRangeBoundary1 `xml:"ToAmt"`

	InnerXml string `xml:",innerxml"`
}

type Garnishment3 struct {
	XMLName xml.Name

	Tp GarnishmentType1 `xml:"Tp"`

	Grnshee *PartyIdentification135 `xml:"Grnshee"`

	GrnshmtAdmstr *PartyIdentification135 `xml:"GrnshmtAdmstr"`

	RefNb *Max140Text `xml:"RefNb"`

	Dt *ISODate `xml:"Dt"`

	RmtdAmt *ActiveOrHistoricCurrencyAndAmount `xml:"RmtdAmt"`

	FmlyMdclInsrncInd *TrueFalseIndicator `xml:"FmlyMdclInsrncInd"`

	MplyeeTermntnInd *TrueFalseIndicator `xml:"MplyeeTermntnInd"`

	InnerXml string `xml:",innerxml"`
}

type GarnishmentType1 struct {
	XMLName xml.Name

	CdOrPrtry GarnishmentType1Choice `xml:"CdOrPrtry"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GarnishmentType1Choice struct {
	XMLName xml.Name

	Cd *ExternalGarnishmentType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type GenericAccountIdentification1 struct {
	XMLName xml.Name

	Id Max34Text `xml:"Id"`

	SchmeNm *AccountSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericFinancialIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	SchmeNm *Max35Text `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericIdentification3 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericIdentification30 struct {
	XMLName xml.Name

	Id Exact4AlphaNumericText `xml:"Id"`

	Issr Max35Text `xml:"Issr"`

	SchmeNm *Max35Text `xml:"SchmeNm"`

	InnerXml string `xml:",innerxml"`
}

type GenericIdentification32 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	Tp *PartyType3Code `xml:"Tp"`

	Issr *PartyType4Code `xml:"Issr"`

	ShrtNm *Max35Text `xml:"ShrtNm"`

	InnerXml string `xml:",innerxml"`
}

type GenericOrganisationIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GenericPersonIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"SchmeNm"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type GroupHeader81 struct {
	XMLName xml.Name

	MsgId Max35Text `xml:"MsgId"`

	CreDtTm ISODateTime `xml:"CreDtTm"`

	MsgRcpt *PartyIdentification135 `xml:"MsgRcpt"`

	MsgPgntn *Pagination1 `xml:"MsgPgntn"`

	OrgnlBizQry *OriginalBusinessQuery1 `xml:"OrgnlBizQry"`

	AddtlInf *Max500Text `xml:"AddtlInf"`

	InnerXml string `xml:",innerxml"`
}

type IdentificationSource3Choice struct {
	XMLName xml.Name

	Cd *ExternalFinancialInstrumentIdentificationType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ImpliedCurrencyAmountRange1Choice struct {
	XMLName xml.Name

	FrAmt *AmountRangeBoundary1 `xml:"FrAmt"`

	ToAmt *AmountRangeBoundary1 `xml:"ToAmt"`

	FrToAmt *FromToAmountRange1 `xml:"FrToAmt"`

	EQAmt *ImpliedCurrencyAndAmount `xml:"EQAmt"`

	NEQAmt *ImpliedCurrencyAndAmount `xml:"NEQAmt"`

	InnerXml string `xml:",innerxml"`
}

type InterestRecord2 struct {
	XMLName xml.Name

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd CreditDebitCode `xml:"CdtDbtInd"`

	Tp *InterestType1Choice `xml:"Tp"`

	Rate *Rate4 `xml:"Rate"`

	FrToDt *DateTimePeriod1 `xml:"FrToDt"`

	Rsn *Max35Text `xml:"Rsn"`

	Tax *TaxCharges2 `xml:"Tax"`

	InnerXml string `xml:",innerxml"`
}

type InterestType1Choice struct {
	XMLName xml.Name

	Cd *InterestType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type LocalInstrument2Choice struct {
	XMLName xml.Name

	Cd *ExternalLocalInstrument1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type MessageIdentification2 struct {
	XMLName xml.Name

	MsgNmId *Max35Text `xml:"MsgNmId"`

	MsgId *Max35Text `xml:"MsgId"`

	InnerXml string `xml:",innerxml"`
}

type NameAndAddress16 struct {
	XMLName xml.Name

	Nm Max140Text `xml:"Nm"`

	Adr PostalAddress24 `xml:"Adr"`

	InnerXml string `xml:",innerxml"`
}

type NumberAndSumOfTransactions1 struct {
	XMLName xml.Name

	NbOfNtries *Max15NumericText `xml:"NbOfNtries"`

	Sum *DecimalNumber `xml:"Sum"`

	InnerXml string `xml:",innerxml"`
}

type NumberAndSumOfTransactions4 struct {
	XMLName xml.Name

	NbOfNtries *Max15NumericText `xml:"NbOfNtries"`

	Sum *DecimalNumber `xml:"Sum"`

	TtlNetNtry *AmountAndDirection35 `xml:"TtlNetNtry"`

	InnerXml string `xml:",innerxml"`
}

type OrganisationIdentification29 struct {
	XMLName xml.Name

	AnyBIC *AnyBICDec2014Identifier `xml:"AnyBIC"`

	LEI *LEIIdentifier `xml:"LEI"`

	Othr []GenericOrganisationIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type OrganisationIdentificationSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalOrganisationIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type OriginalAndCurrentQuantities1 struct {
	XMLName xml.Name

	FaceAmt ImpliedCurrencyAndAmount `xml:"FaceAmt"`

	AmtsdVal ImpliedCurrencyAndAmount `xml:"AmtsdVal"`

	InnerXml string `xml:",innerxml"`
}

type OriginalBusinessQuery1 struct {
	XMLName xml.Name

	MsgId Max35Text `xml:"MsgId"`

	MsgNmId *Max35Text `xml:"MsgNmId"`

	CreDtTm *ISODateTime `xml:"CreDtTm"`

	InnerXml string `xml:",innerxml"`
}

type OtherContact1 struct {
	XMLName xml.Name

	ChanlTp Max4Text `xml:"ChanlTp"`

	Id *Max128Text `xml:"Id"`

	InnerXml string `xml:",innerxml"`
}

type OtherIdentification1 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	Sfx *Max16Text `xml:"Sfx"`

	Tp IdentificationSource3Choice `xml:"Tp"`

	InnerXml string `xml:",innerxml"`
}

type Pagination1 struct {
	XMLName xml.Name

	PgNb Max5NumericText `xml:"PgNb"`

	LastPgInd YesNoIndicator `xml:"LastPgInd"`

	InnerXml string `xml:",innerxml"`
}

type Party38Choice struct {
	XMLName xml.Name

	OrgId *OrganisationIdentification29 `xml:"OrgId"`

	PrvtId *PersonIdentification13 `xml:"PrvtId"`

	InnerXml string `xml:",innerxml"`
}

type Party40Choice struct {
	XMLName xml.Name

	Pty *PartyIdentification135 `xml:"Pty"`

	Agt *BranchAndFinancialInstitutionIdentification6 `xml:"Agt"`

	InnerXml string `xml:",innerxml"`
}

type PartyIdentification135 struct {
	XMLName xml.Name

	Nm *Max140Text `xml:"Nm"`

	PstlAdr *PostalAddress24 `xml:"PstlAdr"`

	Id *Party38Choice `xml:"Id"`

	CtryOfRes *CountryCode `xml:"CtryOfRes"`

	CtctDtls *Contact4 `xml:"CtctDtls"`

	InnerXml string `xml:",innerxml"`
}

type PaymentCard4 struct {
	XMLName xml.Name

	PlainCardData *PlainCardData1 `xml:"PlainCardData"`

	CardCtryCd *Exact3NumericText `xml:"CardCtryCd"`

	CardBrnd *GenericIdentification1 `xml:"CardBrnd"`

	AddtlCardData *Max70Text `xml:"AddtlCardData"`

	InnerXml string `xml:",innerxml"`
}

type PaymentContext3 struct {
	XMLName xml.Name

	CardPres *TrueFalseIndicator `xml:"CardPres"`

	CrdhldrPres *TrueFalseIndicator `xml:"CrdhldrPres"`

	OnLineCntxt *TrueFalseIndicator `xml:"OnLineCntxt"`

	AttndncCntxt *AttendanceContext1Code `xml:"AttndncCntxt"`

	TxEnvt *TransactionEnvironment1Code `xml:"TxEnvt"`

	TxChanl *TransactionChannel1Code `xml:"TxChanl"`

	AttndntMsgCpbl *TrueFalseIndicator `xml:"AttndntMsgCpbl"`

	AttndntLang *ISO2ALanguageCode `xml:"AttndntLang"`

	CardDataNtryMd CardDataReading1Code `xml:"CardDataNtryMd"`

	FllbckInd *TrueFalseIndicator `xml:"FllbckInd"`

	AuthntcnMtd *CardholderAuthentication2 `xml:"AuthntcnMtd"`

	InnerXml string `xml:",innerxml"`
}

type PaymentReturnReason5 struct {
	XMLName xml.Name

	OrgnlBkTxCd *BankTransactionCodeStructure4 `xml:"OrgnlBkTxCd"`

	Orgtr *PartyIdentification135 `xml:"Orgtr"`

	Rsn *ReturnReason5Choice `xml:"Rsn"`

	AddtlInf []Max105Text `xml:"AddtlInf"`

	InnerXml string `xml:",innerxml"`
}

type PaymentTypeInformation27 struct {
	XMLName xml.Name

	InstrPrty *Priority2Code `xml:"InstrPrty"`

	ClrChanl *ClearingChannel2Code `xml:"ClrChanl"`

	SvcLvl []ServiceLevel8Choice `xml:"SvcLvl"`

	LclInstrm *LocalInstrument2Choice `xml:"LclInstrm"`

	SeqTp *SequenceType3Code `xml:"SeqTp"`

	CtgyPurp *CategoryPurpose1Choice `xml:"CtgyPurp"`

	InnerXml string `xml:",innerxml"`
}

type PersonIdentification13 struct {
	XMLName xml.Name

	DtAndPlcOfBirth *DateAndPlaceOfBirth1 `xml:"DtAndPlcOfBirth"`

	Othr []GenericPersonIdentification1 `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type PersonIdentificationSchemeName1Choice struct {
	XMLName xml.Name

	Cd *ExternalPersonIdentification1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type PlainCardData1 struct {
	XMLName xml.Name

	PAN Min8Max28NumericText `xml:"PAN"`

	CardSeqNb *Min2Max3NumericText `xml:"CardSeqNb"`

	FctvDt *ISOYearMonth `xml:"FctvDt"`

	XpryDt ISOYearMonth `xml:"XpryDt"`

	SvcCd *Exact3NumericText `xml:"SvcCd"`

	TrckData []TrackData1 `xml:"TrckData"`

	CardSctyCd *CardSecurityInformation1 `xml:"CardSctyCd"`

	InnerXml string `xml:",innerxml"`
}

type PointOfInteraction1 struct {
	XMLName xml.Name

	Id GenericIdentification32 `xml:"Id"`

	SysNm *Max70Text `xml:"SysNm"`

	GrpId *Max35Text `xml:"GrpId"`

	Cpblties *PointOfInteractionCapabilities1 `xml:"Cpblties"`

	Cmpnt []PointOfInteractionComponent1 `xml:"Cmpnt"`

	InnerXml string `xml:",innerxml"`
}

type PointOfInteractionCapabilities1 struct {
	XMLName xml.Name

	CardRdngCpblties []CardDataReading1Code `xml:"CardRdngCpblties"`

	CrdhldrVrfctnCpblties []CardholderVerificationCapability1Code `xml:"CrdhldrVrfctnCpblties"`

	OnLineCpblties *OnLineCapability1Code `xml:"OnLineCpblties"`

	DispCpblties []DisplayCapabilities1 `xml:"DispCpblties"`

	PrtLineWidth *Max3NumericText `xml:"PrtLineWidth"`

	InnerXml string `xml:",innerxml"`
}

type PointOfInteractionComponent1 struct {
	XMLName xml.Name

	POICmpntTp POIComponentType1Code `xml:"POICmpntTp"`

	ManfctrId *Max35Text `xml:"ManfctrId"`

	Mdl *Max35Text `xml:"Mdl"`

	VrsnNb *Max16Text `xml:"VrsnNb"`

	SrlNb *Max35Text `xml:"SrlNb"`

	ApprvlNb []Max70Text `xml:"ApprvlNb"`

	InnerXml string `xml:",innerxml"`
}

type PostalAddress24 struct {
	XMLName xml.Name

	AdrTp *AddressType3Choice `xml:"AdrTp"`

	Dept *Max70Text `xml:"Dept"`

	SubDept *Max70Text `xml:"SubDept"`

	StrtNm *Max70Text `xml:"StrtNm"`

	BldgNb *Max16Text `xml:"BldgNb"`

	BldgNm *Max35Text `xml:"BldgNm"`

	Flr *Max70Text `xml:"Flr"`

	PstBx *Max16Text `xml:"PstBx"`

	Room *Max70Text `xml:"Room"`

	PstCd *Max16Text `xml:"PstCd"`

	TwnNm *Max35Text `xml:"TwnNm"`

	TwnLctnNm *Max35Text `xml:"TwnLctnNm"`

	DstrctNm *Max35Text `xml:"DstrctNm"`

	CtrySubDvsn *Max35Text `xml:"CtrySubDvsn"`

	Ctry *CountryCode `xml:"Ctry"`

	AdrLine []Max70Text `xml:"AdrLine"`

	InnerXml string `xml:",innerxml"`
}

type Price7 struct {
	XMLName xml.Name

	Tp YieldedOrValueType1Choice `xml:"Tp"`

	Val PriceRateOrAmount3Choice `xml:"Val"`

	InnerXml string `xml:",innerxml"`
}

type PriceRateOrAmount3Choice struct {
	XMLName xml.Name

	Rate *PercentageRate `xml:"Rate"`

	Amt *ActiveOrHistoricCurrencyAnd13DecimalAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type Product2 struct {
	XMLName xml.Name

	PdctCd Max70Text `xml:"PdctCd"`

	UnitOfMeasr *UnitOfMeasure1Code `xml:"UnitOfMeasr"`

	PdctQty *DecimalNumber `xml:"PdctQty"`

	UnitPric *ImpliedCurrencyAndAmount `xml:"UnitPric"`

	PdctAmt *ImpliedCurrencyAndAmount `xml:"PdctAmt"`

	TaxTp *Max35Text `xml:"TaxTp"`

	AddtlPdctInf *Max35Text `xml:"AddtlPdctInf"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryAgent4 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Agt BranchAndFinancialInstitutionIdentification6 `xml:"Agt"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryBankTransactionCodeStructure1 struct {
	XMLName xml.Name

	Cd Max35Text `xml:"Cd"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryDate3 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Dt DateAndDateTime2Choice `xml:"Dt"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryParty5 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Pty Party40Choice `xml:"Pty"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryPrice2 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Pric ActiveOrHistoricCurrencyAndAmount `xml:"Pric"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryQuantity1 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Qty Max35Text `xml:"Qty"`

	InnerXml string `xml:",innerxml"`
}

type ProprietaryReference1 struct {
	XMLName xml.Name

	Tp Max35Text `xml:"Tp"`

	Ref Max35Text `xml:"Ref"`

	InnerXml string `xml:",innerxml"`
}

type ProxyAccountIdentification1 struct {
	XMLName xml.Name

	Tp *ProxyAccountType1Choice `xml:"Tp"`

	Id Max2048Text `xml:"Id"`

	InnerXml string `xml:",innerxml"`
}

type ProxyAccountType1Choice struct {
	XMLName xml.Name

	Cd *ExternalProxyAccountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type Purpose2Choice struct {
	XMLName xml.Name

	Cd *ExternalPurpose1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type Rate4 struct {
	XMLName xml.Name

	Tp RateType4Choice `xml:"Tp"`

	VldtyRg *ActiveOrHistoricCurrencyAndAmountRange2 `xml:"VldtyRg"`

	InnerXml string `xml:",innerxml"`
}

type RateType4Choice struct {
	XMLName xml.Name

	Pctg *PercentageRate `xml:"Pctg"`

	Othr *Max35Text `xml:"Othr"`

	InnerXml string `xml:",innerxml"`
}

type ReferredDocumentInformation7 struct {
	XMLName xml.Name

	Tp *ReferredDocumentType4 `xml:"Tp"`

	Nb *Max35Text `xml:"Nb"`

	RltdDt *ISODate `xml:"RltdDt"`

	LineDtls []DocumentLineInformation1 `xml:"LineDtls"`

	InnerXml string `xml:",innerxml"`
}

type ReferredDocumentType3Choice struct {
	XMLName xml.Name

	Cd *DocumentType6Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ReferredDocumentType4 struct {
	XMLName xml.Name

	CdOrPrtry ReferredDocumentType3Choice `xml:"CdOrPrtry"`

	Issr *Max35Text `xml:"Issr"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceAmount2 struct {
	XMLName xml.Name

	DuePyblAmt *ActiveOrHistoricCurrencyAndAmount `xml:"DuePyblAmt"`

	DscntApldAmt []DiscountAmountAndType1 `xml:"DscntApldAmt"`

	CdtNoteAmt *ActiveOrHistoricCurrencyAndAmount `xml:"CdtNoteAmt"`

	TaxAmt []TaxAmountAndType1 `xml:"TaxAmt"`

	AdjstmntAmtAndRsn []DocumentAdjustment1 `xml:"AdjstmntAmtAndRsn"`

	RmtdAmt *ActiveOrHistoricCurrencyAndAmount `xml:"RmtdAmt"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceAmount3 struct {
	XMLName xml.Name

	DuePyblAmt *ActiveOrHistoricCurrencyAndAmount `xml:"DuePyblAmt"`

	DscntApldAmt []DiscountAmountAndType1 `xml:"DscntApldAmt"`

	CdtNoteAmt *ActiveOrHistoricCurrencyAndAmount `xml:"CdtNoteAmt"`

	TaxAmt []TaxAmountAndType1 `xml:"TaxAmt"`

	AdjstmntAmtAndRsn []DocumentAdjustment1 `xml:"AdjstmntAmtAndRsn"`

	RmtdAmt *ActiveOrHistoricCurrencyAndAmount `xml:"RmtdAmt"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceInformation21 struct {
	XMLName xml.Name

	Ustrd []Max140Text `xml:"Ustrd"`

	Strd []StructuredRemittanceInformation17 `xml:"Strd"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceLocation7 struct {
	XMLName xml.Name

	RmtId *Max35Text `xml:"RmtId"`

	RmtLctnDtls []RemittanceLocationData1 `xml:"RmtLctnDtls"`

	InnerXml string `xml:",innerxml"`
}

type RemittanceLocationData1 struct {
	XMLName xml.Name

	Mtd RemittanceLocationMethod2Code `xml:"Mtd"`

	ElctrncAdr *Max2048Text `xml:"ElctrncAdr"`

	PstlAdr *NameAndAddress16 `xml:"PstlAdr"`

	InnerXml string `xml:",innerxml"`
}

type ReportEntry12 struct {
	XMLName xml.Name

	NtryRef *Max35Text `xml:"NtryRef"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	CdtDbtInd CreditDebitCode `xml:"CdtDbtInd"`

	RvslInd *TrueFalseIndicator `xml:"RvslInd"`

	Sts EntryStatus1Choice `xml:"Sts"`

	BookgDt *DateAndDateTime2Choice `xml:"BookgDt"`

	ValDt *DateAndDateTime2Choice `xml:"ValDt"`

	AcctSvcrRef *Max35Text `xml:"AcctSvcrRef"`

	Avlbty []CashAvailability1 `xml:"Avlbty"`

	BkTxCd BankTransactionCodeStructure4 `xml:"BkTxCd"`

	ComssnWvrInd *YesNoIndicator `xml:"ComssnWvrInd"`

	AddtlInfInd *MessageIdentification2 `xml:"AddtlInfInd"`

	AmtDtls *AmountAndCurrencyExchange3 `xml:"AmtDtls"`

	Chrgs *Charges6 `xml:"Chrgs"`

	TechInptChanl *TechnicalInputChannel1Choice `xml:"TechInptChanl"`

	Intrst *TransactionInterest4 `xml:"Intrst"`

	CardTx *CardEntry5 `xml:"CardTx"`

	NtryDtls []EntryDetails11 `xml:"NtryDtls"`

	AddtlNtryInf *Max500Text `xml:"AddtlNtryInf"`

	InnerXml string `xml:",innerxml"`
}

type ReportingSource1Choice struct {
	XMLName xml.Name

	Cd *ExternalReportingSource1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type ReturnReason5Choice struct {
	XMLName xml.Name

	Cd *ExternalReturnReason1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type SecuritiesAccount19 struct {
	XMLName xml.Name

	Id Max35Text `xml:"Id"`

	Tp *GenericIdentification30 `xml:"Tp"`

	Nm *Max70Text `xml:"Nm"`

	InnerXml string `xml:",innerxml"`
}

type SecurityIdentification19 struct {
	XMLName xml.Name

	ISIN *ISINOct2015Identifier `xml:"ISIN"`

	OthrId []OtherIdentification1 `xml:"OthrId"`

	Desc *Max140Text `xml:"Desc"`

	InnerXml string `xml:",innerxml"`
}

type SequenceRange1 struct {
	XMLName xml.Name

	FrSeq Max35Text `xml:"FrSeq"`

	ToSeq Max35Text `xml:"ToSeq"`

	InnerXml string `xml:",innerxml"`
}

type SequenceRange1Choice struct {
	XMLName xml.Name

	FrSeq *Max35Text `xml:"FrSeq"`

	ToSeq *Max35Text `xml:"ToSeq"`

	FrToSeq []SequenceRange1 `xml:"FrToSeq"`

	EQSeq []Max35Text `xml:"EQSeq"`

	NEQSeq []Max35Text `xml:"NEQSeq"`

	InnerXml string `xml:",innerxml"`
}

type ServiceLevel8Choice struct {
	XMLName xml.Name

	Cd *ExternalServiceLevel1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type StructuredRemittanceInformation17 struct {
	XMLName xml.Name

	RfrdDocInf []ReferredDocumentInformation7 `xml:"RfrdDocInf"`

	RfrdDocAmt *RemittanceAmount2 `xml:"RfrdDocAmt"`

	CdtrRefInf *CreditorReferenceInformation2 `xml:"CdtrRefInf"`

	Invcr *PartyIdentification135 `xml:"Invcr"`

	Invcee *PartyIdentification135 `xml:"Invcee"`

	TaxRmt *TaxData1 `xml:"TaxRmt"`

	GrnshmtRmt *Garnishment3 `xml:"GrnshmtRmt"`

	AddtlRmtInf []Max140Text `xml:"AddtlRmtInf"`

	InnerXml string `xml:",innerxml"`
}

type SupplementaryData1 struct {
	XMLName xml.Name

	PlcAndNm *Max350Text `xml:"PlcAndNm"`

	Envlp SupplementaryDataEnvelope1 `xml:"Envlp"`

	InnerXml string `xml:",innerxml"`
}

type SupplementaryDataEnvelope1 struct {
	XMLName xml.Name

	InnerXml string `xml:",innerxml"`
}

type TaxAmount3 struct {
	XMLName xml.Name

	Rate *PercentageRate `xml:"Rate"`

	TaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TaxblBaseAmt"`

	TtlAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlAmt"`

	Dtls []TaxRecordDetails3 `xml:"Dtls"`

	InnerXml string `xml:",innerxml"`
}

type TaxAmountAndType1 struct {
	XMLName xml.Name

	Tp *TaxAmountType1Choice `xml:"Tp"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type TaxAmountType1Choice struct {
	XMLName xml.Name

	Cd *ExternalTaxAmountType1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TaxAuthorisation1 struct {
	XMLName xml.Name

	Titl *Max35Text `xml:"Titl"`

	Nm *Max140Text `xml:"Nm"`

	InnerXml string `xml:",innerxml"`
}

type TaxCharges2 struct {
	XMLName xml.Name

	Id *Max35Text `xml:"Id"`

	Rate *PercentageRate `xml:"Rate"`

	Amt *ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type TaxData1 struct {
	XMLName xml.Name

	Cdtr *TaxParty1 `xml:"Cdtr"`

	Dbtr *TaxParty2 `xml:"Dbtr"`

	UltmtDbtr *TaxParty2 `xml:"UltmtDbtr"`

	AdmstnZone *Max35Text `xml:"AdmstnZone"`

	RefNb *Max140Text `xml:"RefNb"`

	Mtd *Max35Text `xml:"Mtd"`

	TtlTaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlTaxblBaseAmt"`

	TtlTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlTaxAmt"`

	Dt *ISODate `xml:"Dt"`

	SeqNb *Number `xml:"SeqNb"`

	Rcrd []TaxRecord3 `xml:"Rcrd"`

	InnerXml string `xml:",innerxml"`
}

type TaxInformation10 struct {
	XMLName xml.Name

	Cdtr *TaxParty1 `xml:"Cdtr"`

	Dbtr *TaxParty2 `xml:"Dbtr"`

	AdmstnZone *Max35Text `xml:"AdmstnZone"`

	RefNb *Max140Text `xml:"RefNb"`

	Mtd *Max35Text `xml:"Mtd"`

	TtlTaxblBaseAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlTaxblBaseAmt"`

	TtlTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlTaxAmt"`

	Dt *ISODate `xml:"Dt"`

	SeqNb *Number `xml:"SeqNb"`

	Rcrd []TaxRecord3 `xml:"Rcrd"`

	InnerXml string `xml:",innerxml"`
}

type TaxParty1 struct {
	XMLName xml.Name

	TaxId *Max35Text `xml:"TaxId"`

	RegnId *Max35Text `xml:"RegnId"`

	TaxTp *Max35Text `xml:"TaxTp"`

	InnerXml string `xml:",innerxml"`
}

type TaxParty2 struct {
	XMLName xml.Name

	TaxId *Max35Text `xml:"TaxId"`

	RegnId *Max35Text `xml:"RegnId"`

	TaxTp *Max35Text `xml:"TaxTp"`

	Authstn *TaxAuthorisation1 `xml:"Authstn"`

	InnerXml string `xml:",innerxml"`
}

type TaxPeriod3 struct {
	XMLName xml.Name

	Yr *ISOYear `xml:"Yr"`

	Tp *TaxRecordPeriod1Code `xml:"Tp"`

	FrToDt *DatePeriod2 `xml:"FrToDt"`

	InnerXml string `xml:",innerxml"`
}

type TaxRecord3 struct {
	XMLName xml.Name

	Tp *Max35Text `xml:"Tp"`

	Ctgy *Max35Text `xml:"Ctgy"`

	CtgyDtls *Max35Text `xml:"CtgyDtls"`

	DbtrSts *Max35Text `xml:"DbtrSts"`

	CertId *Max35Text `xml:"CertId"`

	FrmsCd *Max35Text `xml:"FrmsCd"`

	Prd *TaxPeriod3 `xml:"Prd"`

	TaxAmt *TaxAmount3 `xml:"TaxAmt"`

	AddtlInf *Max140Text `xml:"AddtlInf"`

	InnerXml string `xml:",innerxml"`
}

type TaxRecordDetails3 struct {
	XMLName xml.Name

	Prd *TaxPeriod3 `xml:"Prd"`

	Amt ActiveOrHistoricCurrencyAndAmount `xml:"Amt"`

	InnerXml string `xml:",innerxml"`
}

type TechnicalInputChannel1Choice struct {
	XMLName xml.Name

	Cd *ExternalTechnicalInputChannel1Code `xml:"Cd"`

	Prtry *Max35Text `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TotalTransactions6 struct {
	XMLName xml.Name

	TtlNtries *NumberAndSumOfTransactions4 `xml:"TtlNtries"`

	TtlCdtNtries *NumberAndSumOfTransactions1 `xml:"TtlCdtNtries"`

	TtlDbtNtries *NumberAndSumOfTransactions1 `xml:"TtlDbtNtries"`

	TtlNtriesPerBkTxCd []TotalsPerBankTransactionCode5 `xml:"TtlNtriesPerBkTxCd"`

	InnerXml string `xml:",innerxml"`
}

type TotalsPerBankTransactionCode5 struct {
	XMLName xml.Name

	NbOfNtries *Max15NumericText `xml:"NbOfNtries"`

	Sum *DecimalNumber `xml:"Sum"`

	TtlNetNtry *AmountAndDirection35 `xml:"TtlNetNtry"`

	CdtNtries *NumberAndSumOfTransactions1 `xml:"CdtNtries"`

	DbtNtries *NumberAndSumOfTransactions1 `xml:"DbtNtries"`

	FcstInd *TrueFalseIndicator `xml:"FcstInd"`

	BkTxCd BankTransactionCodeStructure4 `xml:"BkTxCd"`

	Avlbty []CashAvailability1 `xml:"Avlbty"`

	Dt *DateAndDateTime2Choice `xml:"Dt"`

	InnerXml string `xml:",innerxml"`
}

type TrackData1 struct {
	XMLName xml.Name

	TrckNb *Exact1NumericText `xml:"TrckNb"`

	TrckVal Max140Text `xml:"TrckVal"`

	InnerXml string `xml:",innerxml"`
}

type TransactionAgents5 struct {
	XMLName xml.Name

	InstgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstgAgt"`

	InstdAgt *BranchAndFinancialInstitutionIdentification6 `xml:"InstdAgt"`

	DbtrAgt *BranchAndFinancialInstitutionIdentification6 `xml:"DbtrAgt"`

	CdtrAgt *BranchAndFinancialInstitutionIdentification6 `xml:"CdtrAgt"`

	IntrmyAgt1 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt1"`

	IntrmyAgt2 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt2"`

	IntrmyAgt3 *BranchAndFinancialInstitutionIdentification6 `xml:"IntrmyAgt3"`

	RcvgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"RcvgAgt"`

	DlvrgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"DlvrgAgt"`

	IssgAgt *BranchAndFinancialInstitutionIdentification6 `xml:"IssgAgt"`

	SttlmPlc *BranchAndFinancialInstitutionIdentification6 `xml:"SttlmPlc"`

	Prtry []ProprietaryAgent4 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TransactionDates3 struct {
	XMLName xml.Name

	AccptncDtTm *ISODateTime `xml:"AccptncDtTm"`

	TradActvtyCtrctlSttlmDt *ISODate `xml:"TradActvtyCtrctlSttlmDt"`

	TradDt *ISODate `xml:"TradDt"`

	IntrBkSttlmDt *ISODate `xml:"IntrBkSttlmDt"`

	StartDt *ISODate `xml:"StartDt"`

	EndDt *ISODate `xml:"EndDt"`

	TxDtTm *ISODateTime `xml:"TxDtTm"`

	Prtry []ProprietaryDate3 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TransactionIdentifier1 struct {
	XMLName xml.Name

	TxDtTm ISODateTime `xml:"TxDtTm"`

	TxRef Max35Text `xml:"TxRef"`

	InnerXml string `xml:",innerxml"`
}

type TransactionInterest4 struct {
	XMLName xml.Name

	TtlIntrstAndTaxAmt *ActiveOrHistoricCurrencyAndAmount `xml:"TtlIntrstAndTaxAmt"`

	Rcrd []InterestRecord2 `xml:"Rcrd"`

	InnerXml string `xml:",innerxml"`
}

type TransactionParties9 struct {
	XMLName xml.Name

	InitgPty *Party40Choice `xml:"InitgPty"`

	Dbtr *Party40Choice `xml:"Dbtr"`

	DbtrAcct *CashAccount40 `xml:"DbtrAcct"`

	UltmtDbtr *Party40Choice `xml:"UltmtDbtr"`

	Cdtr *Party40Choice `xml:"Cdtr"`

	CdtrAcct *CashAccount40 `xml:"CdtrAcct"`

	UltmtCdtr *Party40Choice `xml:"UltmtCdtr"`

	TradgPty *Party40Choice `xml:"TradgPty"`

	Prtry []ProprietaryParty5 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TransactionPrice4Choice struct {
	XMLName xml.Name

	DealPric *Price7 `xml:"DealPric"`

	Prtry []ProprietaryPrice2 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TransactionQuantities3Choice struct {
	XMLName xml.Name

	Qty *FinancialInstrumentQuantity1Choice `xml:"Qty"`

	OrgnlAndCurFaceAmt *OriginalAndCurrentQuantities1 `xml:"OrgnlAndCurFaceAmt"`

	Prtry *ProprietaryQuantity1 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type TransactionReferences6 struct {
	XMLName xml.Name

	MsgId *Max35Text `xml:"MsgId"`

	AcctSvcrRef *Max35Text `xml:"AcctSvcrRef"`

	PmtInfId *Max35Text `xml:"PmtInfId"`

	InstrId *Max35Text `xml:"InstrId"`

	EndToEndId *Max35Text `xml:"EndToEndId"`

	UETR *UUIDv4Identifier `xml:"UETR"`

	TxId *Max35Text `xml:"TxId"`

	MndtId *Max35Text `xml:"MndtId"`

	ChqNb *Max35Text `xml:"ChqNb"`

	ClrSysRef *Max35Text `xml:"ClrSysRef"`

	AcctOwnrTxId *Max35Text `xml:"AcctOwnrTxId"`

	AcctSvcrTxId *Max35Text `xml:"AcctSvcrTxId"`

	MktInfrstrctrTxId *Max35Text `xml:"MktInfrstrctrTxId"`

	PrcgId *Max35Text `xml:"PrcgId"`

	Prtry []ProprietaryReference1 `xml:"Prtry"`

	InnerXml string `xml:",innerxml"`
}

type YieldedOrValueType1Choice struct {
	XMLName xml.Name

	Yldd *YesNoIndicator `xml:"Yldd"`

	ValTp *PriceValueType1Code `xml:"ValTp"`

	InnerXml string `xml:",innerxml"`
}

// XSD SimpleType declarations

type ActiveCurrencyAndAmountSimpleType float64

type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAnd13DecimalAmountSimpleType float64

type ActiveOrHistoricCurrencyAndAmountSimpleType float64

type ActiveOrHistoricCurrencyCode string

type AddressType2Code string

const AddressType2CodeAddr AddressType2Code = "ADDR"

const AddressType2CodePbox AddressType2Code = "PBOX"

const AddressType2CodeHome AddressType2Code = "HOME"

const AddressType2CodeBizz AddressType2Code = "BIZZ"

const AddressType2CodeMlto AddressType2Code = "MLTO"

const AddressType2CodeDlvy AddressType2Code = "DLVY"

type AnyBICDec2014Identifier string

type AttendanceContext1Code string

const AttendanceContext1CodeAttd AttendanceContext1Code = "ATTD"

const AttendanceContext1CodeSatt AttendanceContext1Code = "SATT"

const AttendanceContext1CodeUatt AttendanceContext1Code = "UATT"

type AuthenticationEntity1Code string

const AuthenticationEntity1CodeIccd AuthenticationEntity1Code = "ICCD"

const AuthenticationEntity1CodeAgnt AuthenticationEntity1Code = "AGNT"

const AuthenticationEntity1CodeMerc AuthenticationEntity1Code = "MERC"

type AuthenticationMethod1Code string

const AuthenticationMethod1CodeUknw AuthenticationMethod1Code = "UKNW"

const AuthenticationMethod1CodeByps AuthenticationMethod1Code = "BYPS"

const AuthenticationMethod1CodeNpin AuthenticationMethod1Code = "NPIN"

const AuthenticationMethod1CodeFpin AuthenticationMethod1Code = "FPIN"

const AuthenticationMethod1CodeCpsg AuthenticationMethod1Code = "CPSG"

const AuthenticationMethod1CodePpsg AuthenticationMethod1Code = "PPSG"

const AuthenticationMethod1CodeManu AuthenticationMethod1Code = "MANU"

const AuthenticationMethod1CodeMerc AuthenticationMethod1Code = "MERC"

const AuthenticationMethod1CodeScrt AuthenticationMethod1Code = "SCRT"

const AuthenticationMethod1CodeSnct AuthenticationMethod1Code = "SNCT"

const AuthenticationMethod1CodeScnl AuthenticationMethod1Code = "SCNL"

type BICFIDec2014Identifier string

type BaseOneRate float64

type CSCManagement1Code string

const CSCManagement1CodePrst CSCManagement1Code = "PRST"

const CSCManagement1CodeByps CSCManagement1Code = "BYPS"

const CSCManagement1CodeUnrd CSCManagement1Code = "UNRD"

const CSCManagement1CodeNcsc CSCManagement1Code = "NCSC"

type CardDataReading1Code string

const CardDataReading1CodeTagc CardDataReading1Code = "TAGC"

const CardDataReading1CodePhys CardDataReading1Code = "PHYS"

const CardDataReading1CodeBrcd CardDataReading1Code = "BRCD"

const CardDataReading1CodeMgst CardDataReading1Code = "MGST"

const CardDataReading1CodeCicc CardDataReading1Code = "CICC"

const CardDataReading1CodeDfle CardDataReading1Code = "DFLE"

const CardDataReading1CodeCtls CardDataReading1Code = "CTLS"

const CardDataReading1CodeEctl CardDataReading1Code = "ECTL"

type CardPaymentServiceType2Code string

const CardPaymentServiceType2CodeAggr CardPaymentServiceType2Code = "AGGR"

const CardPaymentServiceType2CodeDccv CardPaymentServiceType2Code = "DCCV"

const CardPaymentServiceType2CodeGrtt CardPaymentServiceType2Code = "GRTT"

const CardPaymentServiceType2CodeInsp CardPaymentServiceType2Code = "INSP"

const CardPaymentServiceType2CodeLoyt CardPaymentServiceType2Code = "LOYT"

const CardPaymentServiceType2CodeNres CardPaymentServiceType2Code = "NRES"

const CardPaymentServiceType2CodePuco CardPaymentServiceType2Code = "PUCO"

const CardPaymentServiceType2CodeRecp CardPaymentServiceType2Code = "RECP"

const CardPaymentServiceType2CodeSoaf CardPaymentServiceType2Code = "SOAF"

const CardPaymentServiceType2CodeUnaf CardPaymentServiceType2Code = "UNAF"

const CardPaymentServiceType2CodeVcau CardPaymentServiceType2Code = "VCAU"

type CardholderVerificationCapability1Code string

const CardholderVerificationCapability1CodeMnsg CardholderVerificationCapability1Code = "MNSG"

const CardholderVerificationCapability1CodeNpin CardholderVerificationCapability1Code = "NPIN"

const CardholderVerificationCapability1CodeFcpn CardholderVerificationCapability1Code = "FCPN"

const CardholderVerificationCapability1CodeFepn CardholderVerificationCapability1Code = "FEPN"

const CardholderVerificationCapability1CodeFdsg CardholderVerificationCapability1Code = "FDSG"

const CardholderVerificationCapability1CodeFbio CardholderVerificationCapability1Code = "FBIO"

const CardholderVerificationCapability1CodeMnvr CardholderVerificationCapability1Code = "MNVR"

const CardholderVerificationCapability1CodeFbig CardholderVerificationCapability1Code = "FBIG"

const CardholderVerificationCapability1CodeApki CardholderVerificationCapability1Code = "APKI"

const CardholderVerificationCapability1CodePkis CardholderVerificationCapability1Code = "PKIS"

const CardholderVerificationCapability1CodeChdt CardholderVerificationCapability1Code = "CHDT"

const CardholderVerificationCapability1CodeScec CardholderVerificationCapability1Code = "SCEC"

type ChargeBearerType1Code string

const ChargeBearerType1CodeDebt ChargeBearerType1Code = "DEBT"

const ChargeBearerType1CodeCred ChargeBearerType1Code = "CRED"

const ChargeBearerType1CodeShar ChargeBearerType1Code = "SHAR"

const ChargeBearerType1CodeSlev ChargeBearerType1Code = "SLEV"

type ChargeIncludedIndicator bool

type ClearingChannel2Code string

const ClearingChannel2CodeRtgs ClearingChannel2Code = "RTGS"

const ClearingChannel2CodeRtns ClearingChannel2Code = "RTNS"

const ClearingChannel2CodeMpns ClearingChannel2Code = "MPNS"

const ClearingChannel2CodeBook ClearingChannel2Code = "BOOK"

type CopyDuplicate1Code string

const CopyDuplicate1CodeCodu CopyDuplicate1Code = "CODU"

const CopyDuplicate1CodeCopy CopyDuplicate1Code = "COPY"

const CopyDuplicate1CodeDupl CopyDuplicate1Code = "DUPL"

type CountryCode string

type CreditDebitCode string

const CreditDebitCodeCrdt CreditDebitCode = "CRDT"

const CreditDebitCodeDbit CreditDebitCode = "DBIT"

type DecimalNumber float64

type DocumentType3Code string

const DocumentType3CodeRadm DocumentType3Code = "RADM"

const DocumentType3CodeRpin DocumentType3Code = "RPIN"

const DocumentType3CodeFxdr DocumentType3Code = "FXDR"

const DocumentType3CodeDisp DocumentType3Code = "DISP"

const DocumentType3CodePuor DocumentType3Code = "PUOR"

const DocumentType3CodeScor DocumentType3Code = "SCOR"

type DocumentType6Code string

const DocumentType6CodeMsin DocumentType6Code = "MSIN"

const DocumentType6CodeCnfa DocumentType6Code = "CNFA"

const DocumentType6CodeDnfa DocumentType6Code = "DNFA"

const DocumentType6CodeCinv DocumentType6Code = "CINV"

const DocumentType6CodeCren DocumentType6Code = "CREN"

const DocumentType6CodeDebn DocumentType6Code = "DEBN"

const DocumentType6CodeHiri DocumentType6Code = "HIRI"

const DocumentType6CodeSbin DocumentType6Code = "SBIN"

const DocumentType6CodeCmcn DocumentType6Code = "CMCN"

const DocumentType6CodeSoac DocumentType6Code = "SOAC"

const DocumentType6CodeDisp DocumentType6Code = "DISP"

const DocumentType6CodeBold DocumentType6Code = "BOLD"

const DocumentType6CodeVchr DocumentType6Code = "VCHR"

const DocumentType6CodeAroi DocumentType6Code = "AROI"

const DocumentType6CodeTsut DocumentType6Code = "TSUT"

const DocumentType6CodePuor DocumentType6Code = "PUOR"

type Exact1NumericText string

type Exact3NumericText string

type Exact4AlphaNumericText string

type ExternalAccountIdentification1Code string

type ExternalBankTransactionDomain1Code string

type ExternalBankTransactionFamily1Code string

type ExternalBankTransactionSubFamily1Code string

type ExternalCardTransactionCategory1Code string

type ExternalCashAccountType1Code string

type ExternalCategoryPurpose1Code string

type ExternalChargeType1Code string

type ExternalClearingSystemIdentification1Code string

type ExternalDiscountAmountType1Code string

type ExternalDocumentLineType1Code string

type ExternalEntryStatus1Code string

type ExternalFinancialInstitutionIdentification1Code string

type ExternalFinancialInstrumentIdentificationType1Code string

type ExternalGarnishmentType1Code string

type ExternalLocalInstrument1Code string

type ExternalOrganisationIdentification1Code string

type ExternalPersonIdentification1Code string

type ExternalProxyAccountType1Code string

type ExternalPurpose1Code string

type ExternalRePresentmentReason1Code string

type ExternalReportingSource1Code string

type ExternalReturnReason1Code string

type ExternalServiceLevel1Code string

type ExternalTaxAmountType1Code string

type ExternalTechnicalInputChannel1Code string

type IBAN2007Identifier string

type ISINOct2015Identifier string

type ISO2ALanguageCode string

type ISODate string

type ISODateTime string

type ISOYear string

type ISOYearMonth string

type ImpliedCurrencyAndAmount float64

type InterestType1Code string

const InterestType1CodeIndy InterestType1Code = "INDY"

const InterestType1CodeOvrn InterestType1Code = "OVRN"

type LEIIdentifier string

type Max1025Text string

type Max105Text string

type Max128Text string

type Max140Text string

type Max15NumericText string

type Max15PlusSignedNumericText string

type Max16Text string

type Max2048Text string

type Max34Text string

type Max350Text string

type Max35Text string

type Max3NumericText string

type Max4Text string

type Max500Text string

type Max5NumericText string

type Max70Text string

type Min2Max3NumericText string

type Min3Max4NumericText string

type Min8Max28NumericText string

type NamePrefix2Code string

const NamePrefix2CodeDoct NamePrefix2Code = "DOCT"

const NamePrefix2CodeMadm NamePrefix2Code = "MADM"

const NamePrefix2CodeMiss NamePrefix2Code = "MISS"

const NamePrefix2CodeMist NamePrefix2Code = "MIST"

const NamePrefix2CodeMiks NamePrefix2Code = "MIKS"

type NonNegativeDecimalNumber float64

type Number float64

type OnLineCapability1Code string

const OnLineCapability1CodeOfln OnLineCapability1Code = "OFLN"

const OnLineCapability1CodeOnln OnLineCapability1Code = "ONLN"

const OnLineCapability1CodeSmon OnLineCapability1Code = "SMON"

type POIComponentType1Code string

const POIComponentType1CodeSoft POIComponentType1Code = "SOFT"

const POIComponentType1CodeEmvk POIComponentType1Code = "EMVK"

const POIComponentType1CodeEmvo POIComponentType1Code = "EMVO"

const POIComponentType1CodeMrit POIComponentType1Code = "MRIT"

const POIComponentType1CodeChit POIComponentType1Code = "CHIT"

const POIComponentType1CodeSecm POIComponentType1Code = "SECM"

const POIComponentType1CodePedv POIComponentType1Code = "PEDV"

type PartyType3Code string

const PartyType3CodeOpoi PartyType3Code = "OPOI"

const PartyType3CodeMerc PartyType3Code = "MERC"

const PartyType3CodeAccp PartyType3Code = "ACCP"

const PartyType3CodeItag PartyType3Code = "ITAG"

const PartyType3CodeAcqr PartyType3Code = "ACQR"

const PartyType3CodeCiss PartyType3Code = "CISS"

const PartyType3CodeDlis PartyType3Code = "DLIS"

type PartyType4Code string

const PartyType4CodeMerc PartyType4Code = "MERC"

const PartyType4CodeAccp PartyType4Code = "ACCP"

const PartyType4CodeItag PartyType4Code = "ITAG"

const PartyType4CodeAcqr PartyType4Code = "ACQR"

const PartyType4CodeCiss PartyType4Code = "CISS"

const PartyType4CodeTaxh PartyType4Code = "TAXH"

type PercentageRate float64

type PhoneNumber string

type PreferredContactMethod1Code string

const PreferredContactMethod1CodeLett PreferredContactMethod1Code = "LETT"

const PreferredContactMethod1CodeMail PreferredContactMethod1Code = "MAIL"

const PreferredContactMethod1CodePhon PreferredContactMethod1Code = "PHON"

const PreferredContactMethod1CodeFaxx PreferredContactMethod1Code = "FAXX"

const PreferredContactMethod1CodeCell PreferredContactMethod1Code = "CELL"

type PriceValueType1Code string

const PriceValueType1CodeDisc PriceValueType1Code = "DISC"

const PriceValueType1CodePrem PriceValueType1Code = "PREM"

const PriceValueType1CodeParv PriceValueType1Code = "PARV"

type Priority2Code string

const Priority2CodeHigh Priority2Code = "HIGH"

const Priority2CodeNorm Priority2Code = "NORM"

type RemittanceLocationMethod2Code string

const RemittanceLocationMethod2CodeFaxi RemittanceLocationMethod2Code = "FAXI"

const RemittanceLocationMethod2CodeEdic RemittanceLocationMethod2Code = "EDIC"

const RemittanceLocationMethod2CodeUrid RemittanceLocationMethod2Code = "URID"

const RemittanceLocationMethod2CodeEmal RemittanceLocationMethod2Code = "EMAL"

const RemittanceLocationMethod2CodePost RemittanceLocationMethod2Code = "POST"

const RemittanceLocationMethod2CodeSmsm RemittanceLocationMethod2Code = "SMSM"

type SequenceType3Code string

const SequenceType3CodeFrst SequenceType3Code = "FRST"

const SequenceType3CodeRcur SequenceType3Code = "RCUR"

const SequenceType3CodeFnal SequenceType3Code = "FNAL"

const SequenceType3CodeOoff SequenceType3Code = "OOFF"

const SequenceType3CodeRpre SequenceType3Code = "RPRE"

type TaxRecordPeriod1Code string

const TaxRecordPeriod1CodeMm01 TaxRecordPeriod1Code = "MM01"

const TaxRecordPeriod1CodeMm02 TaxRecordPeriod1Code = "MM02"

const TaxRecordPeriod1CodeMm03 TaxRecordPeriod1Code = "MM03"

const TaxRecordPeriod1CodeMm04 TaxRecordPeriod1Code = "MM04"

const TaxRecordPeriod1CodeMm05 TaxRecordPeriod1Code = "MM05"

const TaxRecordPeriod1CodeMm06 TaxRecordPeriod1Code = "MM06"

const TaxRecordPeriod1CodeMm07 TaxRecordPeriod1Code = "MM07"

const TaxRecordPeriod1CodeMm08 TaxRecordPeriod1Code = "MM08"

const TaxRecordPeriod1CodeMm09 TaxRecordPeriod1Code = "MM09"

const TaxRecordPeriod1CodeMm10 TaxRecordPeriod1Code = "MM10"

const TaxRecordPeriod1CodeMm11 TaxRecordPeriod1Code = "MM11"

const TaxRecordPeriod1CodeMm12 TaxRecordPeriod1Code = "MM12"

const TaxRecordPeriod1CodeQtr1 TaxRecordPeriod1Code = "QTR1"

const TaxRecordPeriod1CodeQtr2 TaxRecordPeriod1Code = "QTR2"

const TaxRecordPeriod1CodeQtr3 TaxRecordPeriod1Code = "QTR3"

const TaxRecordPeriod1CodeQtr4 TaxRecordPeriod1Code = "QTR4"

const TaxRecordPeriod1CodeHlf1 TaxRecordPeriod1Code = "HLF1"

const TaxRecordPeriod1CodeHlf2 TaxRecordPeriod1Code = "HLF2"

type TransactionChannel1Code string

const TransactionChannel1CodeMail TransactionChannel1Code = "MAIL"

const TransactionChannel1CodeTlph TransactionChannel1Code = "TLPH"

const TransactionChannel1CodeEcom TransactionChannel1Code = "ECOM"

const TransactionChannel1CodeTvpy TransactionChannel1Code = "TVPY"

type TransactionEnvironment1Code string

const TransactionEnvironment1CodeMerc TransactionEnvironment1Code = "MERC"

const TransactionEnvironment1CodePriv TransactionEnvironment1Code = "PRIV"

const TransactionEnvironment1CodePubl TransactionEnvironment1Code = "PUBL"

type TrueFalseIndicator bool

type UUIDv4Identifier string

type UnitOfMeasure1Code string

const UnitOfMeasure1CodePiec UnitOfMeasure1Code = "PIEC"

const UnitOfMeasure1CodeTons UnitOfMeasure1Code = "TONS"

const UnitOfMeasure1CodeFoot UnitOfMeasure1Code = "FOOT"

const UnitOfMeasure1CodeGbga UnitOfMeasure1Code = "GBGA"

const UnitOfMeasure1CodeUsga UnitOfMeasure1Code = "USGA"

const UnitOfMeasure1CodeGram UnitOfMeasure1Code = "GRAM"

const UnitOfMeasure1CodeInch UnitOfMeasure1Code = "INCH"

const UnitOfMeasure1CodeKilo UnitOfMeasure1Code = "KILO"

const UnitOfMeasure1CodePund UnitOfMeasure1Code = "PUND"

const UnitOfMeasure1CodeMetr UnitOfMeasure1Code = "METR"

const UnitOfMeasure1CodeCmet UnitOfMeasure1Code = "CMET"

const UnitOfMeasure1CodeMmet UnitOfMeasure1Code = "MMET"

const UnitOfMeasure1CodeLitr UnitOfMeasure1Code = "LITR"

const UnitOfMeasure1CodeCeli UnitOfMeasure1Code = "CELI"

const UnitOfMeasure1CodeMili UnitOfMeasure1Code = "MILI"

const UnitOfMeasure1CodeGbou UnitOfMeasure1Code = "GBOU"

const UnitOfMeasure1CodeUsou UnitOfMeasure1Code = "USOU"

const UnitOfMeasure1CodeGbqa UnitOfMeasure1Code = "GBQA"

const UnitOfMeasure1CodeUsqa UnitOfMeasure1Code = "USQA"

const UnitOfMeasure1CodeGbpi UnitOfMeasure1Code = "GBPI"

const UnitOfMeasure1CodeUspi UnitOfMeasure1Code = "USPI"

const UnitOfMeasure1CodeMile UnitOfMeasure1Code = "MILE"

const UnitOfMeasure1CodeKmet UnitOfMeasure1Code = "KMET"

const UnitOfMeasure1CodeYard UnitOfMeasure1Code = "YARD"

const UnitOfMeasure1CodeSqki UnitOfMeasure1Code = "SQKI"

const UnitOfMeasure1CodeHect UnitOfMeasure1Code = "HECT"

const UnitOfMeasure1CodeAres UnitOfMeasure1Code = "ARES"

const UnitOfMeasure1CodeSmet UnitOfMeasure1Code = "SMET"

const UnitOfMeasure1CodeScmt UnitOfMeasure1Code = "SCMT"

const UnitOfMeasure1CodeSmil UnitOfMeasure1Code = "SMIL"

const UnitOfMeasure1CodeSqmi UnitOfMeasure1Code = "SQMI"

const UnitOfMeasure1CodeSqya UnitOfMeasure1Code = "SQYA"

const UnitOfMeasure1CodeSqfo UnitOfMeasure1Code = "SQFO"

const UnitOfMeasure1CodeSqin UnitOfMeasure1Code = "SQIN"

const UnitOfMeasure1CodeAcre UnitOfMeasure1Code = "ACRE"

type UserInterface2Code string

const UserInterface2CodeMdsp UserInterface2Code = "MDSP"

const UserInterface2CodeCdsp UserInterface2Code = "CDSP"

type YesNoIndicator bool
